### ISSUE TITLE
Trigger to be checked 

### ISSUE THREAD

**Issue by jedori0228** [CMSSNU/SKFlatMaker#16]
From #9, we cleaned up triggers.

Please check if your analysis trigger is missing.

[2016] https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0016/log_2016_MC_1.log
[2017] https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0016/log_2017_MC_1.log

**Comment by jedori0228** [comment]
From #9, we cleaned up triggers.

Please check if your analysis trigger is missing.

[2016] https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0016/log_2016_MC.log
[2017] https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0016/log_2017_MC.log

**Comment by jbhyun** [comment]
In 2016 trigger list, please also add 
1. HLT_IsoTkMu24_v* 
2. HLT_TripleMu_12_10_5_v* 
3. HLT_DiMu9_Ele9_CaloIdL_TrackIdL_v*

**Comment by jedori0228** [comment]
Hi @jbhyun,

I added

**Comment by jedori0228** [comment]
Thanks @jbhyun .

Here is the updated lines : https://github.com/jedori0228/SKFlatMaker/commit/094e8a146097628d482e4b55e7422f4e7e336f8d

I put removed and current triggers below.

* for the changed trigger txt file,
* removed : < [SKFlatMaker::hltReport] 
* added : > [SKFlatMaker::hltReport] 

[2016]
Changed triggers : https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0009/diff_2016_Triggers_3.txt
Current triggers saved : https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0009/log_2016_AfterTriggerClean_3.log

[2017]
Changed triggers : https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0009/diff_2017_Triggers_3.txt
Current triggers saved : https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0009/log_2017_AfterTriggerClean_3.log

**Comment by jedori0228** [comment]
By the way, can we remove triggers with "eta2p1"?
I see quite many of them in the current list, but we've never used them before.

**Comment by jbhyun** [comment]
It is okay for trileptonic H+ analysis.

**Comment by jedori0228** [comment]
I think is is also okay for HN analysis. I think we can remove it for now.

**Comment by jedori0228** [comment]
eta2p1 removed : https://github.com/jedori0228/SKFlatMaker/commit/8b55793028c7a0e9c433ba1985aab7411717dc8c

[2016]
Changed triggers : https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0009/diff_2016_Triggers_4.txt
Current triggers saved : https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0009/log_2016_AfterTriggerClean_4.log

[2017]
Changed triggers : https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0009/diff_2017_Triggers_4.txt
Current triggers saved : https://jskim.web.cern.ch/jskim/SKFlat/Development/Issue_0009/log_2017_AfterTriggerClean_4.log

I think the current trigger lists are good.

Is this okay?

**Comment by sihyunjeon** [comment]
@jedori0228  I think all the needed changes have been made then

**Comment by jedori0228** [comment]
Okay, PR created : #17
