### ISSUE TITLE
2016 Egamma ID

### ISSUE THREAD

**Issue by jedori0228** [CMSSNU/SKFlatMaker#29]
Should we use the same VIDs for both 2016 and 2017 as below?

https://github.com/CMSSNU/SKFlatMaker/blob/2a39620275d0bd173a3414f06688fb0d67c19508/SKFlatMaker/script/CRAB3/RunSKFlatMaker.py#L167-L172

Or, for 2016, use 2016 version as below?

https://github.com/CMSSNU/SKFlatMaker/blob/f9d510a294ade4dbc74dc5a98d89e152389f2cef/SKFlatMaker/script/CRAB3/RunSKFlatMaker.py#L172-L174

**Comment by d4space** [comment]
Hi Jae Sung,

The cut-based id is different btw "94X and later” and “2016 and for 80X and later” as [*1].
Each of them is optimized for 2017 and 2016 data respectively.
Thus, I think we need to use them separately for each 2016 legacy and 2017 even though the CMSSW 94X used for both of them.

Thanks,
SangEun.


[*1] https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2#Working%20points%20for%202016%20data%20for <https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2#Working points for 2016 data for>

**Comment by jedori0228** [comment]
Thank you @d4space !

I created a PR for this here : #30

**Comment by jedori0228** [comment]
solved in #30
