### ISSUE TITLE
2017 JEC+JER SFs updated

### ISSUE THREAD

**Issue by jedori0228** [CMSSNU/SKFlatMaker#31]
https://hypernews.cern.ch/HyperNews/CMS/get/jes/806.html

Will be applied in the next production (maybe next year with 2018 update?)

**Comment by sungbinoh** [comment]
1. Global tags from two references
[1] https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC
[2] https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVAnalysisSummaryTable
2016
DATA : 94X_dataRun2_v10
MC : 94X_mcRun2_asymptotic_v3 (Affected by FormulaEvaluator bug! [1])
2017
DATA : 94X_dataRun2_v11
MC : 94X_mc2017_realistic_v17
2018
DATA : 102X_dataRun2_Prompt_v11 ([2]) OR 102X_dataRun2_Prompt_v12 ([1])
MC : 102X_upgrade2018_realistic_v12 ([2]) OR 102X_upgrade2018_realistic_v16 ([1])

followed [1] on the code for now.
./SKFlatMaker/script/CRAB3/RunSKFlatMaker.py
./SKFlatMaker/script/PDF/RunSKFlatMaker.py

**Comment by jedori0228** [comment]
Done
