### ISSUE TITLE
Official L1 Prefiering reweight recipe

### ISSUE THREAD

**Issue by jedori0228** [CMSSNU/SKFlatMaker#32]
https://twiki.cern.ch/twiki/bin/view/CMS/L1ECALPrefiringWeightRecipe

**Comment by sungbinoh** [comment]
1. There are two kind of maps for jet
eta VS emPt (PT from ECAL)
eta VS Pt 

Because the L1 Prefiring is coming from ECAL,
it will be better to use the map of eta VS emPt.
How about you think?

**Comment by jedori0228** [comment]
check #37
