### ISSUE TITLE
Next Production : Run2Legacy_v3

### ISSUE THREAD

**Issue by jedori0228** [CMSSNU/SKFlatMaker#44]
Add anything if it needs to be added in the next production.

**Comment by jedori0228** [comment]
1. 2017 Tag can be changed
We've been using 94X_dataRun2_v6_fixJECJER (94X_mc2017_realistic_v14_fixJECJER) for 2017 DATA(MC), but in PdmV summary slide,
it is recommend to use 94X_dataRun2_v11 (94X_mc2017_realistic_v17).
I found they are (almost, except "IOV" but I don't think it is important) identical;
diff in DATA : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v6_fixJECJER/94X_dataRun2_v11
diff in MC : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v14_fixJECJER/94X_mc2017_realistic_v17

**Comment by sungbinoh** [comment]
2. Can we add this sampless for the next production?

/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM
Status: VALID Type: mc Dataset size: 2700321267240 (2.7TB) Number of blocks: 172 Number of events: 71026861 Number of files: 990

**Comment by jalmond** [comment]
Are these only for 2018 samples?

**Comment by sungbinoh** [comment]
Yeah, I thought you would produce 2018 samples only.

**Comment by jedori0228** [comment]
This can be closed by now.
