### ISSUE TITLE
Preparing Run2Legacy_v4

### ISSUE THREAD

**Issue by jedori0228** [CMSSNU/SKFlatMaker#52]
Let's start our next production; Run2Legacy_v3

Things in my list :

- Lepton MVA (https://twiki.cern.ch/twiki/bin/view/CMS/LeptonMVA)
- Update JEC/JER/GT

Add more if you have some..

**Comment by jedori0228** [comment]
- Add HLT objects for trigger matching of leptons

**Comment by sansan9401** [comment]
Optional LHE level info?  (for binned DY sample)

**Comment by jedori0228** [comment]
References
Muon LeptonMVA : https://twiki.cern.ch/twiki/bin/viewauth/CMS/SWGuideMuonIdRun2#Lepton_MVA
Muon trigger matching : https://twiki.cern.ch/twiki/bin/viewauth/CMS/SWGuideMuonIdRun2#Trigger_Muon_matching_since_CMSS

**Comment by jedori0228** [comment]
> * Add HLT objects for trigger matching of leptons

Saving all HLT objects (process.recoTree.StoreHLTObjectFlag = true) increases the file size by 40%. I think it's too much for the central production.. Let's save it later if we really need this..

**Comment by jedori0228** [comment]
Summary 

- [ ] Lepton MVA (https://twiki.cern.ch/twiki/bin/view/CMS/LeptonMVA)
Update JEC/JER/GT
- [ ] Update JEC/JER/GT
- [ ] Add HLT objects for trigger matching of leptons
- [ ] Muon LeptonMVA
- [ ] Optional LHE level info? (for binned DY sample)

**Comment by jedori0228** [comment]
Run2Legacy_v4 tag is created
