### ISSUE TITLE
Additional variables for new SKTree (Run2Legacy_v5)

### ISSUE THREAD

**Issue by joonblee** [CMSSNU/SKFlatMaker#62]
Due date: 2020.NOV.20 (Fri)

**Comment by wonpoint4** [comment]
Jet : boolean of the jet matched to gen jet (True/False)
MET : pfMET with type0,1, phi correction - this is recommendation for pfMET, however we have pfMET without type0
           I am not sure pfMET has better or comparable performance than puppiMET

**Comment by jbhyun** [comment]
MET: Puppi-MET& systematic variation of this
Trigger matching - 1 integer
   - saving all filter information is way too heavy. I plan to add matching information only for a few specified filters.
     last digit will be used for pass/fail (1/0), remaining digits will be used for indicating the fired filers

**Comment by jbhyun** [comment]
> Jet : boolean of the jet matched to gen jet (True/False)
> MET : pfMET with type0,1, phi correction - this is recommendation for pfMET, however we have pfMET without type0
> I am not sure pfMET has better or comparable performance than puppiMET
Actually POG recommendation is only type-1 MET (https://twiki.cern.ch/twiki/bin/view/CMS/MissingET#Recommendations_and_important_li)
but one can apply xy corrections provided by POG if needed, and xy-shift correction is already stored in SKFlat ntuples.
What I understand from the twiki is that though puppi-MET is not officially recommended, it is still acceptable. 
Regarding the performance, dependence on PU modelling is much smaller (Fig 16, https://arxiv.org/pdf/2003.00503.pdf)

**Comment by Hooooon12** [comment]
GenInfo : would like to add second mother and first/second daughter's index.
Currently we have only the index of the first mother of each gen particles.

**Comment by sihyunjeon** [comment]
> GenInfo : would like to add second mother and first/second daughter's index.
> Currently we have only the index of the first mother of each gen particles.

Is there a reason to add the 2nd mother? It is usually not used. "p[0] p[1] > z" process Z's moth1 moth2 are p[0] and p[1], but for other particles usually the second mother isn't filled, no?

**Comment by Hooooon12** [comment]
> > GenInfo : would like to add second mother and first/second daughter's index.
> > Currently we have only the index of the first mother of each gen particles.
> 
> Is there a reason to add the 2nd mother? It is usually not used. "p[0] p[1] > z" process Z's moth1 moth2 are p[0] and p[1], but for other particles usually the second mother isn't filled, no?

Yes, you're right. I originally imagined looking into the two mothers and two daughters systematically.
But the second mother is rarely recorded in hard process except the initial partons, as Sihyun pointed out.
Thanks for the correction.

**Comment by joonblee** [comment]
GenJet: It also corresponds to @wonpoint4 's requirement and type1 HN team also needs this variable.
