### ISSUE TITLE
Plan for Run2UltraLegacy_v3

### ISSUE THREAD

**Issue by sansan9401** [CMSSNU/SKFlatMaker#63]
**Lepton** 
- [x] Electron L1 pt variable for TnP
  * #72 
- [x] Muon medium ID variables 
  * #68
- [x] tau object
  * #76 
  * #78
---
**Jet**
- [x] GenHFHadronMatcher and BJetEnergyCorrectionNN 
  * #69
  * #70
- [x] fatjet_particleNet* variables
  * #73
- [x] Remove CSVv2 variables and reduce DeepJet variables
  * #71
- [x] Fix fatjet ID
  * #79 
---
**MET**
- [x] puppiMET 
  * #74
- [x] reduce pfMET shifts variables
  * #77
---
**Else**
- [x]  Pythia weights
  * #64
  * #67
- [x] code for PrivateMC 
  * #66
- [x] new rho variable
  * #80 
- [x] adding missing TkMu HLT paths
  * #83 
- [x] Update README  
  
~~- [ ] Gen jet matching~~: We can use *jet_GenHFHadronMatcher_flavour!=-999*
~~- [ ] AK4 puppi jet~~: @Hooooon12 checked it doesn't help his analysis

**Comment by sihyunjeon** [comment]
@sansan9401 Please add here todo : FatJet_particleNet* variables. I will do it (though, when is the due?)
